### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by thecodeduchess** [RobvanBeek/dasmoto#1]
https://github.com/RobvanBeek/dasmoto/blob/6cb4521c32eeefeb8ad168d4bd0bb6ddce27de05/index.html#L12-L20

This is really great. Perhaps you could space the different sections, just so it's easier to decern what part is what.  Ias the little sections get longer, it might be easier to see large sections at a glance :)

**Comment by RobvanBeek** [comment]
thanks. I will also add some comment
